### ISSUE TITLE
Finality Providers stop sending Finality sigs

### ISSUE THREAD

**Issue by filippos47** [babylonchain/finality-provider#219]
On our latest devnet with 100 FPs, 75% of the FPs gradually stopped sending sigs in the space of 12 hours. Unfortunately, I didn't have debug log enabled so we don't know the reason.

Example pod:

![2024-01-30_16:17:02](https://github.com/babylonchain/finality-provider/assets/35352222/a0a47111-aa8a-45c8-a978-c6213e9fffab)

**Comment by gitferry** [comment]
addressed by #228
