### ISSUE TITLE
bug: `LastProcessedHeight` leads to blocks never being voted if previously skipped

### ISSUE THREAD

**Issue by vitsalis** [babylonchain/finality-provider#227]
There are two scenarios:

1. During normal operation, a block is skipped for some reason (e.g. due to a bug like the one on #225 ) and the next one is voted (e.g. heights `N` and `N+1`). The last processed height is set to `N+1`, leading to the block at height `N` never being voted for.
2. During fast sync, some blocks might be skipped due to a call to [shouldSubmitFinalitySignature](https://github.com/babylonchain/finality-provider/blob/8473c52206998efe5f542ca772d8694d625b6764/finality-provider/service/fastsync.go#L52), which might return `false` even for cases where a signature should be submitted to the future (e.g. no public randomness available right now). The end of the fast sync [sets LastProcessedHeight](https://github.com/babylonchain/finality-provider/blob/8473c52206998efe5f542ca772d8694d625b6764/finality-provider/service/fastsync.go#L89) to the latest height of the sync, which means that those blocks won't ever be revisited. If it was set to `syncedHeight` we wouldn't have this issue.

In general, the first scenario can be considered as a failsafe for recovering in the case of bugs. The second scenario is a bug and should be resolved (also related to #226 ).

**Comment by gitferry** [comment]
addressed by #228
