### ISSUE TITLE
"unauthorized" error with fpcli register-finality-provider

### ISSUE THREAD

**Issue by johnyangk** [babylonchain/finality-provider#273]
When I run this command

`fpcli register-finality-provider   --btc-pk c3...`

I get this error

`[fpd] rpc error: code = Unknown desc = failed to register the finality-provider to Babylon: unauthorized`

Is registering a new finality provider blocked at this point?

**Comment by gitferry** [comment]
Hey, did you specify chain-id in cli or set it in config? See https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/finality-providers/finality-provider#2-configuration

**Comment by johnyangk** [comment]
I was able to fix the problem with `chain-id`. Thanks for the confirmation!

**Comment by gitferry** [comment]
Thanks for your feedback. Closing this issue now
