### ISSUE TITLE
Requires DATA Prune solutions

### ISSUE THREAD

**Issue by whyrulike** [babylonchain/finality-provider#297]
The growth rate is too fast for the hard disk to support

    1.1T	./data/application.db
    5.4G	./data/state.db
    52K	./data/snapshots/metadata.db
    56K	./data/snapshots
    56K	./data/evidence.db
    8.0G	./data/blockstore.db
    7.9G	./data/tx_index.db
    1015M	./data/cs.wal
    1.1T	./data/

**Comment by gitferry** [comment]
This should be an issue of https://github.com/babylonchain/babylon
