### ISSUE TITLE
Unregistered provider causes program crash

### ISSUE THREAD

**Issue by whyrulike** [babylonchain/finality-provider#301]
fatal	terminating the finality-provider instance due to critical error	
    {"pk": "xxxxxxxx", 
    "error": "reached max failed cycles with err: failed to commit public randomness to the consumer chain: rpc error: code = Unknown desc = rpc error: code = Unknown desc = 
    failed to execute message; message index: 0: the finality provider with BTC PK [] is not registered: the finality provider is not found 
    [cosmossdk.io/errors@v1.0.1/errors.go:155] with gas used: '69665': unknown request"
    }
    
    The fatal error directly causes the program to crash.

**Comment by gitferry** [comment]
This fatal error is intended to crash the daemon.
