### ISSUE TITLE
CLI fpd keys export

### ISSUE THREAD

**Issue by RafilxTenfen** [babylonchain/finality-provider#304]
`fpd keys export [key-name]` 
Export prints the private key of one key in the keyring

**Comment by gitferry** [comment]
is this completed? @RafilxTenfen Feel free to close it if so

**Comment by RafilxTenfen** [comment]
@gitferry nop, still needs to be done

**Comment by RafilxTenfen** [comment]
Done when migrated the CLI to cobra
