### ISSUE TITLE
Finality provider instance fails to start if finalized epoch < registered epoch

### ISSUE THREAD

**Issue by gusin13** [babylonchain/finality-provider#327]
If a finality provider is created and registered simultaneously its possible that finalized epoch is less than registered epoch, in that case the finality provider instance will fail to start and exit. 

https://github.com/babylonchain/finality-provider/blob/6e5545086a253d53c71ebf906d818ae1e1c2ca1d/finality-provider/service/fp_instance.go#L80-L86

Ideally there should be some kind of retry or wait to let checkpoints finalize. cc @SebastianElvis

**Comment by SebastianElvis** [comment]
The entire concept of `registeredEpoch` will be removed, together with BIP-32 scheme. Will address this issue by replacing BIP-32 with the Merkle tree approach

**Comment by gitferry** [comment]
closing this for now as it will be part of timestamping randomness
