### ISSUE TITLE
make sure `mock-gen` always runs when there is an interface update

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/finality-provider#344]
#318 has some issue that i later fixed in #335 

but the CI/CD pipeline failed to detect it b/c it didn't run `make mock-gen`

**Comment by bap2pecs** [comment]
<img width="860" alt="image" src="https://github.com/babylonchain/finality-provider/assets/111917526/4d016820-29e5-496e-8864-b75ac6b21d64">

@gitferry @SebastianElvis found another miss. probably need to prioritize this.

two solutions:
1) add a Git hook to always run `make mock-gen` before a push to remote
2) add a test to run `make mock-gen` and throw if the old and new file doesn't match

**Comment by SebastianElvis** [comment]
Agreed to 1) run `make mock-gen` before `make test` and 2) check mock objects in CI pipeline. Probably let's do 1) first (this is immediately actionable) then do 2) at a later point (this needs some scripting)?

**Comment by bap2pecs** [comment]
actually i was talking to @gitferry on my PR and we agreed that 1) is actually the thing we should avoid. CI should not run mockgen itself but alert if the author forgot to run it

**Comment by bap2pecs** [comment]
git hook IMO is the easiest sol
