### ISSUE TITLE
op-e2e: BBN FP shouldn't use the OP consumer to submit PR and sigs

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/finality-provider#450]
found this weird behavior when debugging. root cause is b/c it shares the same fpApp with OP FPs and the fpApp is configured to use `opcc`:

```
fpApp, err := service.NewFinalityProviderApp(cfg, bc, opcc, eotsCli, fpdb, logger)
```

this doesn't break anything but I am worried that when the tests get complicated it might cause some very hard to debug issues in the future

**Comment by bap2pecs** [comment]
we should figure out a way to set it up properly. another way is to remove the restriction in tests that require a delegation must also delegate to BBN FP. we can add a boolean in the [here](https://github.com/babylonchain/babylon-private/blob/base/consumer-chain-support/x/btcstaking/keeper/btc_delegations.go#L211)

I think although it's a business decision, we can still make our life easier by removing this restriction in e2e test. as I imagine when we add more consumers in the future, it's going to be too complicated to maintain all the FPs in e2e tests

wdyt @SebastianElvis

**Comment by SebastianElvis** [comment]
The finality provider implementation does not allow maintaining FP instances from different consumers. So the e2e test might need to be restructured. I see the following possibilities:

- (preferred) have an admin in the Babylon OP contract, use the admin to inject voting power for the FP, such that FP can submit things to the OP contract
- manually wire a Babylon FP registration request and send to Babylon

CosmWasm e2e uses the admin account approach. Wdyt?

**Comment by bap2pecs** [comment]
> have an admin in the Babylon OP contract, use the admin to inject voting power for the FP, such that FP can submit things to the OP contract. This approach does not involve delegation at all

the doesn't work in our case because we need to query the actual delegation here: https://github.com/babylonchain/babylon-da-sdk/blob/main/sdk/sdk.go#L229-L258

and our current test case already tests that this logic is correct. I think it's good to keep the real delegation in e2e tests to test logic like this since there are so many moving parts in the system so injection should be used carefully

> manually wire a Babylon FP registration request and send to Babylon

yes that's what we are doing in our test but tbh it's not relevant to our code. it's only to satisfy:

```
	if !restakedToBabylon {
		// a BTC delegation has to stake to at least 1 Babylon finality provider
		return false, types.ErrNoBabylonFPRestaked
	}
```

maybe we can build some e2e test infra to make it less confusing

**Comment by bap2pecs** [comment]
this is fixed now as we created `RegisterBBNFinalityProvider()`

it's now fully cleaned up w https://github.com/babylonchain/finality-provider/pull/483/
