### ISSUE TITLE
op e2e: query contract to make sure the submission is there

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/finality-provider#461]
https://github.com/babylonchain/finality-provider/pull/459#discussion_r1663428566

**Comment by bap2pecs** [comment]
discussed w @lesterli offline. once we enable fast sync, we don't need this test case anymore, since it's tested already by fast sync

**Comment by lesterli** [comment]
Enable fast sync https://github.com/babylonchain/finality-provider/pull/484
