### ISSUE TITLE
op e2e: refactor bitcoin rpc url to use `BTCClient`

### ISSUE THREAD

**Issue by parketh** [babylonchain/finality-provider#468]
At the moment when running op e2e tests, we pass in a bitcoin mainnet rpc url to query the block finalization status.

We should refactor this to:
1. use the `BTCClient` interface as per [this](https://github.com/babylonchain/staking-indexer/blob/dev/btcclient/client.go#L17)
2. (optionally) spin up a local `bitcoind` note to bypass rpc rate limits

This issue is related to https://github.com/babylonchain/babylon-da-sdk/issues/41

**Comment by gitferry** [comment]
Here's a reference of how our indexer does the e2e with bitcoind https://github.com/babylonchain/staking-indexer/blob/d085cbfa868f7b45be9b83e72c18911087fd5773/itest/bitcoind_node_setup.go#L38
