### ISSUE TITLE
Make install command cannot working

### ISSUE THREAD

**Issue by AJackTi** [babylonchain/finality-provider#532]
`CGO_CFLAGS="-O -D__BLST_PORTABLE__" go install -mod=readonly --tags "" --ldflags ''  ./...
# github.com/CosmWasm/wasmd/x/wasm/keeper
../go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.50.0/x/wasm/keeper/test_common.go:386:3: cannot use runtime.NewKVStoreService(keys[types.StoreKey]) (value of type "cosmossdk.io/core/store".KVStoreService) as "cosmossdk.io/store/types".StoreKey value in argument to NewKeeper: "cosmossdk.io/core/store".KVStoreService does not implement "cosmossdk.io/store/types".StoreKey (missing method Name)
# github.com/supranational/blst/bindings/go
../go/pkg/mod/github.com/supranational/blst@v0.3.11/bindings/go/rb_tree.go:130:18: undefined: Message
# github.com/cosmos/relayer/v2/relayer/codecs/injective
../go/pkg/mod/github.com/cosmos/relayer/v2@v2.5.2/relayer/codecs/injective/ethsecp256k1.go:200:19: undefined: secp256k1.VerifySignature
make: *** [Makefile:46: install] Error 1`

When I run command **make install**, I got the above error message. Please help me to fix it. 

Environment:
Go version: go1.22.0 linux/amd64
finality-provider release version: v0.2.0

**Comment by liewhite** [comment]
How did you resolve this? I meet the same issue on v0.3.0
