### ISSUE TITLE
Mnemonic for created keyrings should not be stored in the logs

### ISSUE THREAD

**Issue by vitsalis** [babylonchain/finality-provider#78]
When a validator Babylon keyring is created, its mnemonic is included in the logs. This is a security concern as someone having the mnemonic can retrieve the keyring. However, given that we have a test keyring (i.e. unencrypted) this might not improve the security situion.

**Comment by gitferry** [comment]
Now the mnemonic will not be shown in the log. It will be shown after a key is added via `fpd keys add`
